# app/telephony/base.py
from typing import Protocol, Any, Dict

class TelephonyProvider(Protocol):
    name: str

    async def initiate_call(self, to_number: str, from_number: str | None = None) -> str: ...
    def build_say(self, text: str, lang: str = "en") -> str: ...
    def build_gather(self, prompt: str, num_digits: int = 1, input_mode: str = "dtmf", lang: str = "en") -> str: ...
    def wrap_response(self, inner_xml: str) -> str: ...
    def XMLResponse(self, xml: str): ...
    def verify_signature(self, raw_body: bytes, headers: Dict[str, Any], params: Dict[str, str], full_url: str) -> bool: ...
